// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // Use DIRECT_URL for Prisma CLI schema operations when available.
    // This is important for Supabase, where the pooled URL is fine for the app
    // but migrations/db push should use the direct connection.
    url: process.env['DIRECT_URL'] ?? process.env['DATABASE_URL'],
  },
});
